### ISSUE TITLE
export all icons as wel

### ISSUE THREAD

**Issue by ozair-dev** [couetilc/react-social-icons#144]
It'd be cool if I could import all icons.
Also, icons don't load when providing the url without specifying "https" protochol doesn't load.
e.g www.twitter.com won't work

**Comment by couetilc** [comment]
@ozair-dev that is not the case since [v6 of react-social-icons](https://www.npmjs.com/package/react-social-icons).

`<SocialIcon url="www.twitter.com" />` renders the twitter social icon.

If you would like to "import all icons", please open a PR/issue describing the exact use case and a possible API to accomplish it.
