### ISSUE TITLE
Background gets cut off on desktop Safari

### ISSUE THREAD

**Issue by garrytaulu** [couetilc/react-social-icons#147]
I've noticed in some cases the circle background gets cut off on desktop Safari. Note the top edge of the icons in the image below.

<img width="876" alt="image" src="https://user-images.githubusercontent.com/730779/209034683-55d15c79-8311-40fc-bbb5-347f14c2318e.png">

**Comment by couetilc** [comment]
@garrytaulu Webkit is known to have bugs related to SVG rendering. It's particular to this use within the html document rather than endemic to the library. In google chrome and firefox, they render fine. In other situations when using Safari, they render fine. If this affects you in a personal project, try to adjust the CSS or HTML layout to get the results you want from Safari. Unfortunately I can't provide you with a catch-all solution, Safari seems to have its quirks.
